dependencies:
  build:
  - maven:3.3.3
  - java:8.252.09

build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04
    commands:
      - mkdir -p /root/.m2
      - cp mvn-toolchain.xml /root/.m2/toolchains.xml
      - mvn -B deploy checkstyle:checkstyle -Psrc,doc,jenkins -e
ci:
  builds:
    - name: default
      build_target: default
