dependencies:
  build:
  - maven:3.3.3
  - java:8.252.09

build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    commands:
      - mkdir -p /root/.m2
      - cp mvn-toolchain.xml /root/.m2/toolchains.xml
      - mvn clean package checkstyle:checkstyle -Psrc,doc,jenkins -e -Drat.numUnapprovedLicenses=100
ci:
  builds:
    - name: default
      build_target: default
