dependencies:
  build:
  - maven:3.3.3
  - java:8.252.09
    #- java:11.0.8

build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - AGENT_NO_ACCELERATION=1
    commands:
      - mkdir -p /root/.m2
      - cp mvn-toolchain.xml /root/.m2/toolchains.xml
      - mvn install checkstyle:checkstyle -Psrc -e -Drat.numUnapprovedLicenses=100

  - name: default-with-accel
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/yb/tmp/yourbase-junit-agent.jar
    commands:
      - mkdir -p /root/.m2
      - cp mvn-toolchain.xml /root/.m2/toolchains.xml
      - mvn install checkstyle:checkstyle -Psrc -e -Drat.numUnapprovedLicenses=100

  - name: local-1
    container:
      image: yourbase/yb_ubuntu:18.04
      mounts:
        - /Users/jamesnaftel/dev/yourbase/yourbase-java-engine/buildgraph-agent/target/buildgraph-agent-1.0-ALPHA.jar:/yourbase-agent.jar
        - /Users/jamesnaftel/dev/yourbase/yourbase-maven-plugin/target:/root/.m2/repository/io/yourbase/yourbase-maven-plugin/uses-jgitver
    environment:
      - DPKG_FRONTEND=noninteractive
      - YB_AGENT_JAR=/yourbase-agent.jar
      - YB_DEBUG=true
      - YB_BUILD_UUID=build1
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    commands:
      - find . -name "yourbase*.log" -exec rm -f {} \;
      - find . -name "*.ybgraph" -exec rm -f {} \;
      - mkdir -p /root/.m2
      - cp mvn-toolchain.xml /root/.m2/toolchains.xml
      - mvn clean package checkstyle:checkstyle -Psrc -e -Drat.numUnapprovedLicenses=100 -Dmaven.repo.local=/root/.m2/repository

  - name: my
    local_only: true
    container:
      image: yourbase/yb_ubuntu:18.04
      mounts:
        - /Users/jamesnaftel/dev/yourbase/yourbase-java-engine/buildgraph-agent/target/buildgraph-agent-1.0-ALPHA.jar:/yourbase-agent.jar
    environment:
      - DPKG_FRONTEND=noninteractive
      - YB_AGENT_JAR=/Users/jamesnaftel/dev/yourbase/yourbase-java-engine/buildgraph-agent/target/buildgraph-agent-1.0-ALPHA.jar
      - YB_DEBUG=true
      - YB_BUILD_UUID=build1
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    commands:
      - find . -name "yourbase*.log" -exec rm -f {} \;
      - find . -name "*.ybgraph" -exec rm -f {} \;
      - mvn -X clean package checkstyle:checkstyle -Psrc,doc,jenkins -e -Drat.numUnapprovedLicenses=100
ci:
  builds:
    - name: default
      build_target: default

    - name: default-with-accel
      build_target: default-with-accel
